snapshot: lts-23.24
packages:
  - helpers
  - test-helpers
  - dec01
  - dec02
  - dec03
  - dec04
  - dec05
  - dec06
  - dec07
  - dec08
  - dec09
  - dec10
  - dec11
  - dec12
  - dec13
  - dec14
  - dec15
  - dec16
  - dec17
  - dec18
  - dec19
  - dec20
  - dec21
  - dec22
# extra-deps: []
# Override default flag values for local packages and extra-deps
# flags: {}
# Extra package databases containing global packages
# extra-package-dbs: []
