snapshot: lts-22.43
packages:
  - helpers
  - dec01
  - dec02
  - dec03
  - dec04
  - dec05
  - dec06
  - dec07
  - dec08
  - dec09
  - dec10
  - dec11
  - dec12
  - dec13
# extra-deps: []
# Override default flag values for local packages and extra-deps
# flags: {}
# Extra package databases containing global packages
# extra-package-dbs: []
