name:                dec01
version:             0.1.0.0
github:              "tomasaschan/advent-of-code"
license:             BSD-3-Clause
author:              "Tomas Aschan"
maintainer:          "1550920+tomasaschan@users.noreply.github.com"
copyright:           "Tomas Aschan"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - containers
  default-extensions:
  - LambdaCase
  - OverloadedStrings


executables:
  dec01-run:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dec01

tests:
  dec01-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dec01
